version: "3"

services:
  redis:
    image: redis
    restart: always
  api:
    build: ./apiServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
      SERVER_TTL: 24
    ports:
      - 5000:5000
    restart: always
  worker:
    build: ./workerServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
      REDIS_TTL: 604800
      RETRY_COUNT: 5
      DOWNLOAD_DIR: /download
    volumes:
      - /mnt:/download
    restart: always
  redis-insight:
    image: redislabs/redisinsight:latest
    environment:
      RI_REDIS_HOST: redis
    ports:
      - 5540:5540
    depends_on:
      - redis
    restart: always
