version: "3"

services:
  redis:
    image: redis
    restart: always
  api:
    build: ./apiServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
    ports:
      - 5000:5000
    restart: always
  worker:
    build: ./workerServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
      REDIS_TTL: 604800
    volumes:
      - /mnt:/download
    working_dir: /download
    restart: always
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    restart: always
    depends_on:
      - redis
      - api
      - worker