version: "3"

services:
  redis:
    image: redis
    restart: always
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    restart: always
    depends_on:
      - redis
  api:
    build: ./apiServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
    ports:
      - 5000:5000
    restart: always
  worker:
    build: ./workerServer
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis
    volumes:
      - /mnt/video:/download
    working_dir: /download
    restart: always
